sudo: required
language: java
jdk: openjdk8
services: docker

addons:
  apt:
    update: true

env:
  global:
    - NXF_VER=0.32.0
  matrix:
    - TEST=SOMATIC
    - TEST=ANNOTATEVEP
    - TEST=ANNOTATESNPEFF
    - TEST=GERMLINE

install:
  # Install Nextflow
  - curl -fsSL get.nextflow.io | bash
  - chmod +x nextflow
  - sudo mv nextflow /usr/local/bin/
  # Donwload big containers for ANNOTATEVEP and ANNOTATESNPEF tests)
  - "travis_retry ./scripts/containers.sh --profile docker --test $TEST"

# Build references when needed
before_script: "./scripts/test.sh --profile docker --test $TEST --build"

# Actual tests
script: "./scripts/test.sh --profile docker --test $TEST"
