sudo: required
language: java
jdk: openjdk8
services: docker

addons:
  apt:
    update: true

env:
  global:
    - NXF_VER=0.31.0 SGT_VER=2.5.1
  matrix:
    - CE=singularity TEST=SOMATIC
    - CE=docker      TEST=SOMATIC
    - CE=docker      TEST=ANNOTATEVEP
    - CE=singularity TEST=ANNOTATESNPEFF
    - CE=docker      TEST=ANNOTATESNPEFF
    - CE=singularity TEST=GERMLINE
    - CE=docker      TEST=GERMLINE

install:
  # Install Nextflow (and Singularity if needed)
  - "./scripts/install.sh --engine $CE"
  # Donwload big containers for ANNOTATEVEP and ANNOTATESNPEF tests)
  - "travis_retry ./scripts/containers.sh --profile $CE --test $TEST"

# Build references when needed
before_script: "./scripts/test.sh --profile $CE --test $TEST --build"

# Actual tests
script: "./scripts/test.sh --profile $CE --test $TEST"
