# You can use this file to create a conda environment:
#   conda env create -f environment.yml
name: sarek-qctools-2.0
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda-forge::openjdk=8.0.144
  - fastqc=0.11.7
  - multiqc=1.5
  - qualimap=2.2.2a
  - vcftools=0.1.15
