# You can use this file to create a conda environment:
#   conda env create -f environment.yml
name: sarek-vcftools-2.0
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
- vcftools=0.1.15
